---
suse-12.1:
  x86_64:
    sles12-sp1-pool:
      name: "SLES12-SP1-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/SLES/12.1/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP1/x86_64/product"
      ask_on_error: false
    sles12-sp1-updates:
      name: "SLES12-SP1-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP1:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update"
      ask_on_error: false
    sle12-sp1-ha-pool:
      name: "SLE12-SP1-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/sle-ha/12.1/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP1/x86_64/product"
      ask_on_error: false
    sle12-sp1-ha-updates:
      name: "SLE12-SP1-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP1:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP1/x86_64/update"
      ask_on_error: false
    suse-enterprise-storage-3-pool:
      name: "SUSE-Enterprise-Storage-3-Pool"
      required: "optional"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:Update:Products:SES3/ses/3/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/Storage/3/x86_64/product"
      ask_on_error: false
    suse-enterprise-storage-3-updates:
      name: "SUSE-Enterprise-Storage-3-Updates"
      required: "optional"
      features: ["ceph"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:2.1:x86_64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/Storage/3/x86_64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
