---
suse-12.1:
  x86_64:
    sles12-sp1-pool:
      name: "SLES12-SP1-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/SLES/12.1/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP1/x86_64/product"
      ask_on_error: false
    sles12-sp1-updates:
      name: "SLES12-SP1-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP1:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update"
      ask_on_error: false
    sle12-sp1-ha-pool:
      name: "SLE12-SP1-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/sle-ha/12.1/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP1/x86_64/product"
      ask_on_error: false
    sle12-sp1-ha-updates:
      name: "SLE12-SP1-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP1:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP1/x86_64/update"
      ask_on_error: false
    suse-enterprise-storage-3-pool:
      name: "SUSE-Enterprise-Storage-3-Pool"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:Update:Products:SES3/ses/3/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/Storage/3/x86_64/product"
      ask_on_error: false
    suse-enterprise-storage-3-updates:
      name: "SUSE-Enterprise-Storage-3-Updates"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:3:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/Storage/3/x86_64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
suse-12.2:
  aarch64:
    sles12-sp2-pool:
      name: "SLES12-SP2-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/SLES/12.2/POOL/aarch64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP2/aarch64/product"
      ask_on_error: false
    sles12-sp2-updates:
      name: "SLES12-SP2-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP2:aarch64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP2/aarch64/update"
      ask_on_error: false
    sle12-sp2-ha-pool:
      name: "SLE12-SP2-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/sle-ha/12.2/POOL/aarch64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP2/aarch64/product"
      ask_on_error: false
    sle12-sp2-ha-updates:
      name: "SLE12-SP2-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP2:aarch64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP2/aarch64/update"
      ask_on_error: false
    suse-enterprise-storage-4-pool:
      name: "SUSE-Enterprise-Storage-4-Pool"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:SES4/ses/4/POOL/aarch64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/Storage/4/aarch64/product"
      ask_on_error: false
    suse-enterprise-storage-4-updates:
      name: "SUSE-Enterprise-Storage-4-Updates"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:4:aarch64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/Storage/4/aarch64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
  x86_64:
    sles12-sp2-pool:
      name: "SLES12-SP2-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/SLES/12.2/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP2/x86_64/product"
      ask_on_error: false
    sles12-sp2-updates:
      name: "SLES12-SP2-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP2:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP2/x86_64/update"
      ask_on_error: false
    sle12-sp2-ha-pool:
      name: "SLE12-SP2-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/sle-ha/12.2/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP2/x86_64/product"
      ask_on_error: false
    sle12-sp2-ha-updates:
      name: "SLE12-SP2-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP2:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP2/x86_64/update"
      ask_on_error: false
    suse-enterprise-storage-4-pool:
      name: "SUSE-Enterprise-Storage-4-Pool"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:SES4/ses/4/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/Storage/4/x86_64/product"
      ask_on_error: false
    suse-enterprise-storage-4-updates:
      name: "SUSE-Enterprise-Storage-4-Updates"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:4:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/Storage/4/x86_64/update"
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
