---
suse-12.1:
  x86_64:
    sles12-sp1-pool:
      name: "SLES12-SP1-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/SLES/12.1/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP1/x86_64/product"
      ask_on_error: false
    sles12-sp1-updates:
      name: "SLES12-SP1-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP1:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Mitaka/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Staging/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7/suse-openstack-cloud/7/cd/x86_64"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    suse-openstack-cloud-7-pool:
      name: "SUSE-OpenStack-Cloud-7-Pool"
      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/POOL/x86_64"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/OpenStack-Cloud/7/x86_64/product"
      ask_on_error: false
    suse-openstack-cloud-7-updates:
      name: "SUSE-OpenStack-Cloud-7-Updates"
      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:OpenStack-Cloud:7:x86_64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/OpenStack-Cloud/7/x86_64/update"
      ask_on_error: false
    sle12-sp1-ha-pool:
      name: "SLE12-SP1-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/sle-ha/12.1/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP1/x86_64/product"
      ask_on_error: false
    sle12-sp1-ha-updates:
      name: "SLE12-SP1-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP1:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP1/x86_64/update"
      ask_on_error: false
    suse-enterprise-storage-2_1-pool:
      name: "SUSE-Enterprise-Storage-2.1-Pool"
      required: "optional"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:Update:Products:SES2.1/ses/2.1/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/Storage/2.1/x86_64/product"
      ask_on_error: false
    suse-enterprise-storage-2_1-updates:
      name: "SUSE-Enterprise-Storage-2.1-Updates"
      required: "optional"
      features: ["ceph"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:2.1:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/Storage/2.1/x86_64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
  s390x:
    sles12-sp1-pool:
      name: "SLES12-SP1-Pool"
      required: "optional"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/SLES/12.1/POOL/s390x"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP1/s390x/product"
      ask_on_error: false
    sles12-sp1-updates:
      name: "SLES12-SP1-Updates"
      required: "optional"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP1:s390x/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP1/s390x/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/cd/s390x",
              "obsproduct://build.suse.de/Devel:Cloud:7:Staging/suse-openstack-cloud/7/cd/s390x",
              "obsproduct://build.suse.de/Devel:Cloud:7/suse-openstack-cloud/7/cd/s390x"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
